load("@bazel_skylib//rules:build_test.bzl", "build_test")

build_test(
    name = "sources",
    targets = [
        "//test/baremetal:hex",
        "//test/c:hex",
        "//test/c++:hex",
    ],
)
